
language: node_js
node_js:
- stable
branches:
  only:
  - master
  - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
  - node_modules
before_script:
- npx -p greenkeeper-lockfile@1 greenkeeper-lockfile-update
script:
- yarn build
- yarn test
after_script:
- npx codecov
- npx -p greenkeeper-lockfile@1 greenkeeper-lockfile-upload
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist
  github-token: $GH_TOKEN
  on:
    branch: master
notifications:
  email: false
