
/**
  * THIS IS AN AUTOGENERATED FILE
  *
  * You may add your new components/routes during development to avoid restarting the
  * development server, but DO NOT add any extra functionality to this file.
  */

export * from './article'
export * from './comment'
export * from './tags'
export * from './user'
