
/**
  * THIS IS AN AUTOGENERATED FILE
  *
  * You may add your new components/routes during development to avoid restarting the
  * development server, but DO NOT add any extra functionality to this file.
  */

export { default as article } from './article'
export { default as auth } from './auth'
export { default as home } from './home'
export { default as settings } from './settings'
