
/**
  * THIS IS AN AUTOGENERATED FILE
  *
  * You may add your new components/routes during development to avoid restarting the
  * development server, but DO NOT add any extra functionality to this file.
  */

export default {
  'app-footer': () => import('./app-footer'),
  'app-header': () => import('./app-header'),
} as { [k: string]: () => Promise<KnockoutComponentTypes.Config> }
