
/**
  * THIS IS AN AUTOGENERATED FILE
  *
  * You may add your new components/routes during development to avoid restarting the
  * development server, but DO NOT add any extra functionality to this file.
  */

export default {
  'app-footer': () => import('./app-footer'),
  'app-header': () => import('./app-header'),
  'article-meta': () => import('./article-meta'),
  'comment-form': () => import('./comment-form'),
  'comment-list': () => import('./comment-list'),
} as { [k: string]: () => Promise<any> }
