#!/bin/sh

AUTOGEN_BANNER="
/**
  * THIS IS AN AUTOGENERATED FILE
  *
  * You may add your new components/routes during development to avoid restarting the
  * development server, but DO NOT add any extra functionality to this file.
  */
"

MANIFEST=src/components/manifest.ts
echo "Generating src/components/manifest.ts... \c"
echo "$AUTOGEN_BANNER" > $MANIFEST
echo "export default {" >> $MANIFEST
for file in src/components/*
do
  if [ -d $file ]
  then
    component=$(basename $file)
    echo "  '$component': () => import('./$component')," >> $MANIFEST
  fi
done
echo "} as { [k: string]: () => Promise<KnockoutComponentTypes.Config> }" >> $MANIFEST
echo "Done!\n"

MANIFEST=src/views/manifest.ts
echo "Generating src/views/manifest.ts... \c"
echo "$AUTOGEN_BANNER" > $MANIFEST
for file in src/views/*
do
  if [ -d $file ]
  then
    view=$(basename $file)
    echo "export { default as $view } from './$view'" >> $MANIFEST
  fi
done
printf "Done!\n"